version: "3"
services:
  consumer:
    container_name: consumer
    build:
      context: consumer
      dockerfile: Dockerfile-consumer
    restart: on-failure
    env_file:
      - consumer/env/.env
    ports:
      - "40000:40000"
    depends_on:
      - cache
  cache:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    command:
      - redis-server --save 20 1 --loglevel warning --requirepass redisPass
    volumes:
      - cache:/data
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - envs/.env
    volumes:
      - db./2. Init Database:/docker-entrypoint-initdb.d
      - db:/var/lib/postgresql/data

